"""
report_generator.py - Generate PDF analysis reports using fpdf2
"""

from fpdf import FPDF
from datetime import datetime
import os
import tempfile
import numpy as np
import cv2


class CellAnalysisReport(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_fill_color(30, 60, 120)
        self.set_text_color(255, 255, 255)
        self.cell(0, 14, "Cell Image Analysis Report", align="C", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Cell Analysis Platform", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(220, 230, 245)
        self.cell(0, 8, title, fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def key_value(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.cell(70, 7, key + ":", new_x="RIGHT", new_y="LAST")
        self.set_font("Helvetica", "", 10)
        self.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")


def generate_report(
    image_filename: str,
    summary: dict,
    annotated_image: np.ndarray,
    session_name: str = "",
    notes: str = ""
) -> bytes:
    """
    Generate a PDF report and return it as bytes.
    """
    pdf = CellAnalysisReport()
    pdf.add_page()

    # --- Session Info ---
    pdf.section_title("Analysis Details")
    pdf.key_value("Session", session_name or "Unnamed")
    pdf.key_value("Image File", image_filename)
    pdf.key_value("Analysis Date", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    pdf.key_value("Detection Method", summary.get("detection_method", "N/A"))
    pdf.ln(4)

    # --- Summary Stats ---
    pdf.section_title("Detection Summary")
    pdf.key_value("Total Cells Detected", str(summary.get("total_cells", 0)))
    pdf.key_value("Healthy Cells", str(summary.get("healthy_cells", 0)))
    pdf.key_value("Abnormal Cells", str(summary.get("abnormal_cells", 0)))
    pdf.key_value("Average Confidence", f"{summary.get('confidence_avg', 0):.1%}")

    total = summary.get("total_cells", 1) or 1
    abnormal = summary.get("abnormal_cells", 0)
    pdf.key_value("Abnormal Rate", f"{abnormal / total:.1%}")
    pdf.ln(4)

    # --- Class breakdown ---
    class_counts = summary.get("class_counts", {})
    if class_counts:
        pdf.section_title("Cell Type Breakdown")
        for cls, count in class_counts.items():
            pct = count / total * 100
            pdf.key_value(cls, f"{count} ({pct:.1f}%)")
        pdf.ln(4)

    # --- Annotated image ---
    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
        tmp_path = tmp.name
        rgb_image = cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB)
        import PIL.Image
        pil_img = PIL.Image.fromarray(rgb_image)
        pil_img.save(tmp_path, "JPEG", quality=85)

    try:
        pdf.section_title("Annotated Image")
        # Fit image to page width
        page_width = pdf.w - 2 * pdf.l_margin
        pdf.image(tmp_path, x=pdf.l_margin, w=page_width)
    finally:
        os.unlink(tmp_path)

    # --- Notes ---
    if notes:
        pdf.ln(4)
        pdf.section_title("Analyst Notes")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, notes)

    # --- Disclaimer ---
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5,
        "DISCLAIMER: This report is generated by an automated AI system. "
        "Results should be reviewed and validated by a qualified medical or research professional. "
        "Not intended for clinical diagnosis."
    )

    return bytes(pdf.output())
